config/routes.rb
Rails.application.routes.draw do

  # You can have the root of your site routed with "root"
  root to: 'dashboards#dashboard_1'


  resources :hotels
  resources :regions
  resources :towns
  resources :services


  # All routes
  get "dashboards/dashboard_1"
  get "dashboards/dashboard_2"
  get "dashboards/dashboard_3"
  get "dashboards/dashboard_4"
  get "dashboards/dashboard_4_1"
  get "dashboards/dashboard_5"

  get "layoutsoptions/index"
  get "layoutsoptions/off_canvas"

  get "graphs/flot"
  get "graphs/morris"
  get "graphs/rickshaw"
  get "graphs/chartjs"
  get "graphs/chartist"
  get "graphs/peity"
  get "graphs/sparkline"
  get "graphs/c3charts"

  get "mailbox/inbox"
  get "mailbox/email_view"
  get "mailbox/compose_email"
  get "mailbox/email_templates"
  get "mailbox/basic_action_email"
  get "mailbox/alert_email"
  get "mailbox/billing_email"

  get "metrics/index"

  get "widgets/index"

  get "forms/basic_forms"
  get "forms/advanced"
  get "forms/wizard"
  get "forms/file_upload"
  get "forms/text_editor"
  get "forms/markdown"

  get "appviews/contacts"
  get "appviews/profile"
  get "appviews/profile_two"
  get "appviews/contacts_two"
  get "appviews/projects"
  get "appviews/project_detail"
  get "appviews/file_menager"
  get "appviews/vote_list"
  get "appviews/calendar"
  get "appviews/faq"
  get "appviews/timeline"
  get "appviews/pin_board"
  get "appviews/teams_board"
  get "appviews/social_feed"
  get "appviews/clients"
  get "appviews/outlook_view"
  get "appviews/blog"
  get "appviews/article"
  get "appviews/issue_tracker"

  get "pages/search_results"
  get "pages/lockscreen"
  get "pages/invoice"
  get "pages/invoice_print"
  get "pages/login"
  get "pages/login_2"
  get "pages/forgot_password"
  get "pages/register"
  get "pages/not_found_error"
  get "pages/internal_server_error"
  get "pages/empty_page"

  get "miscellaneous/notification"
  get "miscellaneous/nestablelist"
  get "miscellaneous/timeline_second_version"
  get "miscellaneous/forum_view"
  get "miscellaneous/forum_post_view"
  get "miscellaneous/google_maps"
  get "miscellaneous/code_editor"
  get "miscellaneous/modal_window"
  get "miscellaneous/validation"
  get "miscellaneous/tree_view"
  get "miscellaneous/chat_view"
  get "miscellaneous/agile_board"
  get "miscellaneous/diff"
  get "miscellaneous/sweet_alert"
  get "miscellaneous/idle_timer"
  get "miscellaneous/spinners"
  get "miscellaneous/live_favicon"
  get "miscellaneous/masonry"
  get "miscellaneous/tour"
  get "miscellaneous/loading_buttons"
  get "miscellaneous/clipboard"
  get "miscellaneous/truncate"
  get "miscellaneous/i18support"

  get "uielements/typography"
  get "uielements/icons"
  get "uielements/draggable_panels"
  get "uielements/resizeable_panels"
  get "uielements/buttons"
  get "uielements/video"
  get "uielements/tables_panels"
  get "uielements/tabs"
  get "uielements/notifications_tooltips"
  get "uielements/badges_labels_progress"

  get "gridoptions/index"

  get "tables/static_tables"
  get "tables/data_tables"
  get "tables/foo_tables"
  get "tables/jqgrid"

  get "commerce/products_grid"
  get "commerce/products_list"
  get "commerce/product_edit"
  get "commerce/product_detail"
  get "commerce/orders"
  get "commerce/cart"
  get "commerce/payments"

  get "gallery/basic_gallery"
  get "gallery/slick_carusela"
  get "gallery/bootstrap_carusela"

  get "cssanimations/index"

  get "landing/index"

end

app/models/town.rb
class Town < ApplicationRecord

  belongs_to :region
  has_many :hotels
  validates :name, :region_id, presence: true

end

app/controllers/towns_controller.rb
class TownsController < ApplicationController
  before_action :set_town, only: [:show, :edit, :update, :destroy]

    def index
      @towns = Town.all

      @town = Town.new
    end

    def new
      @town = Town.new
    end

    def show
      redirect_to towns_path
    end

    def create
      @town = Town.new(town_param)
      if @town.save
        redirect_to @town, success: 'Город успешно создан'
      else
        flash[:danger] = 'Город не создан'
        render 'new'
      end
    end

    def edit
    end

    def update
      if @town.update_attributes(town_param)
        redirect_to towns_path, success: 'Город успешно обновлена'
      else
        flash[:danger] = 'Город не обновлен'
        render :edit
      end
    end

    def destroy
      @town.destroy
      redirect_to @town
    end

    private
    def set_town
      @town = Town.find(params[:id])
    end

    def town_param
      params.require(:town).permit(:name, :region_id)
    end
end

app/views/towns/_form.html.erb
<div class="col-lg-6">
  <div class="ibox float-e-margins">
    <% if @town.errors.any? %>
        <div class="alert alert-danger">
          <h5><%= t('common.errors')  %></h5>
          <ul>
            <%  @town.errors.full_messages.each do |messanges| %>
                <li> <%= messanges %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="ibox-title">
      <h2><%= @town.new_record? ?   "Создать новый город" : "Изменить регион: #{@town.name}" %></h2>
    </div>
    <div class="ibox-content">
      <%= form_for @town do |f| %>

          <div class="form-group">
            <%= f.label 'Регион'%>
            <%= f.collection_select :region_id, Region.all, :id, :name , {prompt: "Выберите регион"}, {class: "form-control"} %>
          </div>

          <div class="form-group">

            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.submit @town.new_record? ? 'Создать' : 'Сохранить' , class: 'btn btn-primary btn-outline' %>
            <%= link_to  'Назад', :back, class: 'btn btn-default' %>
            <% if @town.id != nil %>
                <%= link_to 'Удалить' , town_path(@town),  method: :delete, class: 'btn btn-danger pull-right', data: {confirm: 'Вы уверены?'} %>
            <% end %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/towns/_modal_form.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Новый город</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for @town do |f|  %>
          <div class="modal-body">

            <div class="form-group">
              <%= f.label 'Регион'%>
              <%= f.collection_select :region_id, Region.all, :id, :name , {prompt: "Выберите регион"}, {class: "form-control"} %>

            </div>

            <div class="form-group">
              <%= f.label 'Название города'%>
              <%= f.text_field :name, class: "form-control" %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit @town.new_record? ? 'Сохранить' : 'Создать', class: 'btn btn-primary btn-outline' %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/towns/edit.html.erb
<%= render 'form'%>

app/views/towns/index.html.erb
<%= render 'modal_form'%>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-6">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h2>Все города</h2>
        </div>
        <div class="ibox-content">

          <table class="table table-striped table-bordered table-hover dataTables-example">
            <thead>
            <tr>
              <th>#</th>
              <th>Регион</th>
              <th>Город</th>
              <th>
                <button type="button" class="btn btn-success btn-sm pull-right" data-toggle="modal" data-target="#exampleModalLong">
                  Добавить город
                </button>
              </th>

            </tr>
            </thead>
            <tbody>
            <% @towns.each do |town| %>
                <tr>
                  <th scope="row"><%= town.id %></th>
                  <td><%= Region.find(town.region_id).name %></td>
                  <td><%= town.name %></td>
                  <td><%= link_to 'Изменить', edit_town_path(town), class: ("btn btn-info btn-sm pull-right") %></td>
                </tr>
            <% end %>
            </tbody>
            <tfoot>
            <tr>
              <th>#</th>
              <th>Город</th>
              <th></th>
            </tr>
            </tfoot>
          </table>

        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :javascript do %>

    <script type="text/javascript">


        $(function() {

            $('.dataTables-example').DataTable({
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    {extend: 'print',
                        customize: function (win){
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                        }
                    }
                ]

            });

          /* Init DataTables */
            var oTable = $('#editable').dataTable();

          /* Apply the jEditable handlers to the table */
            oTable.$('td').editable( '../example_ajax.php', {
                "callback": function( sValue, y ) {
                    var aPos = oTable.fnGetPosition( this );
                    oTable.fnUpdate( sValue, aPos[0], aPos[1] );
                },
                "submitdata": function ( value, settings ) {
                    return {
                        "row_id": this.parentNode.getAttribute('id'),
                        "column": oTable.fnGetPosition( this )[2]
                    };
                },

                "width": "90%",
                "height": "100%"
            } );


        });



    </script>

<% end %>